# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.1.1+01d50e5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import graylog
from graylog.rest import ApiException
from graylog.apis.pluginsorggraylogpluginspipelineprocessorsystempipelinesrule_api import PluginsorggraylogpluginspipelineprocessorsystempipelinesruleApi


class TestPluginsorggraylogpluginspipelineprocessorsystempipelinesruleApi(unittest.TestCase):
    """ PluginsorggraylogpluginspipelineprocessorsystempipelinesruleApi unit test stubs """

    def setUp(self):
        self.api = graylog.apis.pluginsorggraylogpluginspipelineprocessorsystempipelinesrule_api.PluginsorggraylogpluginspipelineprocessorsystempipelinesruleApi()

    def tearDown(self):
        pass

    def test_create_from_parser(self):
        """
        Test case for create_from_parser

        Create a processing rule from source
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Delete a processing rule
        """
        pass

    def test_function_descriptors(self):
        """
        Test case for function_descriptors

        Get function descriptors
        """
        pass

    def test_get(self):
        """
        Test case for get

        Get a processing rule
        """
        pass

    def test_get_all(self):
        """
        Test case for get_all

        Get all processing rules
        """
        pass

    def test_get_bulk(self):
        """
        Test case for get_bulk

        Retrieve the named processing rules in bulk
        """
        pass

    def test_parse(self):
        """
        Test case for parse

        Parse a processing rule without saving it
        """
        pass

    def test_update(self):
        """
        Test case for update

        Modify a processing rule
        """
        pass


if __name__ == '__main__':
    unittest.main()
