# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.1.1+01d50e5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import graylog
from graylog.rest import ApiException
from graylog.apis.systemmetrics_api import SystemmetricsApi


class TestSystemmetricsApi(unittest.TestCase):
    """ SystemmetricsApi unit test stubs """

    def setUp(self):
        self.api = graylog.apis.systemmetrics_api.SystemmetricsApi()

    def tearDown(self):
        pass

    def test_by_namespace(self):
        """
        Test case for by_namespace

        Get all metrics of a namespace
        """
        pass

    def test_metric_names(self):
        """
        Test case for metric_names

        Get all metrics keys/names
        """
        pass

    def test_metrics(self):
        """
        Test case for metrics

        Get all metrics
        """
        pass

    def test_multiple_metrics(self):
        """
        Test case for multiple_metrics

        Get the values of multiple metrics at once
        """
        pass

    def test_single_metric(self):
        """
        Test case for single_metric

        Get a single metric
        """
        pass


if __name__ == '__main__':
    unittest.main()
