# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.1.1+01d50e5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class RotationStrategyDescription(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, default_config=None, json_schema=None):
        """
        RotationStrategyDescription - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'default_config': 'object',
            'json_schema': 'object'
        }

        self.attribute_map = {
            'type': 'type',
            'default_config': 'default_config',
            'json_schema': 'json_schema'
        }

        self._type = type
        self._default_config = default_config
        self._json_schema = json_schema

    @property
    def type(self):
        """
        Gets the type of this RotationStrategyDescription.


        :return: The type of this RotationStrategyDescription.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this RotationStrategyDescription.


        :param type: The type of this RotationStrategyDescription.
        :type: str
        """

        self._type = type

    @property
    def default_config(self):
        """
        Gets the default_config of this RotationStrategyDescription.


        :return: The default_config of this RotationStrategyDescription.
        :rtype: object
        """
        return self._default_config

    @default_config.setter
    def default_config(self, default_config):
        """
        Sets the default_config of this RotationStrategyDescription.


        :param default_config: The default_config of this RotationStrategyDescription.
        :type: object
        """

        self._default_config = default_config

    @property
    def json_schema(self):
        """
        Gets the json_schema of this RotationStrategyDescription.


        :return: The json_schema of this RotationStrategyDescription.
        :rtype: object
        """
        return self._json_schema

    @json_schema.setter
    def json_schema(self, json_schema):
        """
        Sets the json_schema of this RotationStrategyDescription.


        :param json_schema: The json_schema of this RotationStrategyDescription.
        :type: object
        """

        self._json_schema = json_schema

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
